.po 1i
.TH GETS 3 Bell
.V 08/15/84 17:20:15
.\" @[$]gets.3	1.6	08/15/84 17:20:15 - Zilog Inc.
.ad
.fi
.SH NAME
gets, fgets \- get a string from a stream
.SH SYNOPSIS
.nf
\fB#include <stdio.h>
.PP
char *gets\fI(s)\fR
\fBchar *s;\fR
.PP
char *fgets\fI(s, n, stream)\fR
\fBchar \fI*s;\fR
\fBFILE \fI*stream;\fR
\fBint \fIn;\fR
.fi
.SH DESCRIPTION
.B Gets
reads a string into
.I s
from the standard input stream
.B stdin.
The string is terminated by a new line
character, that is replaced in
.I s
by a null character.
.B Gets
returns its argument.
.PP
.B Fgets
reads 
.IR n \-1
characters, or up to a new line
character, whichever comes first,
from the
.I stream
into the string
.IR s .
The last character read into
.I s
is followed by a null character.
.I Fgets
returns its first argument.
.SH SEE ALSO
puts(3),
getc(3),
scanf(3),
fread(3),
ferror(3).
.SH DIAGNOSTICS
.B Gets
and
.B fgets
return the constant pointer 
.SM
.B NULL
upon end of file or error.
.SH LIMITATIONS
.B Gets
deletes a new line, and
.B fgets
keeps it.
