.po 1i
.TH GROUP 5 Bell
.V 08/15/84 17:34:42
.\"@[$]group.5	1.3	08/15/84 17:34:42 - Zilog Inc.
.ad
.SH NAME
group \- group file
.SH DESCRIPTION
.B Group
contains for each group the
following information:
.RS
.IP "\ \(bu"
group name
.IP "\ \(bu"
encrypted password
.IP "\ \(bu"
numerical group ID
.IP "\ \(bu"
a comma separated list of all users allowed in the group
.DT
.RE
.PP
This is an ASCII file.
The fields are separated
by colons;
Each group is separated from the next by a new-line.
If the password field is null, no password is demanded.
.PP
This file resides in directory /etc.
Because of the encrypted
passwords, it can and does have general read
permission and can be used, for example,
to map numerical group ID's to names.
.SH FILES
/etc/group
.SH SEE ALSO
newgrp(1),
passwd(1),
crypt(3),
passwd(5).
