.po 1i
.TH CHROOT 2 Bell
.V 08/15/84 17:12:45
.\" @[$]chroot.2	1.4	08/15/84 17:12:45 - Zilog Inc.
.ad
.fi
.SH NAME
chroot \- change root directory
.SH SYNOPSIS
.B int chroot
.I (dirname)
.br
.B char
.I *dirname;
.SH DESCRIPTION
.I Dirname
is the address of the pathname of a directory,
terminated by a null byte.
.B Chroot
sets the root directory, the
starting point for path names beginning with /.
The call is restricted to the super-user.
.SH SEE ALSO
cd(1), chdir(2).
.SH DIAGNOSTICS
.B Chroot
will fail and the root directory will remain unchanged if
one or more of the following are true:
.IP
Any component of the
path name
is not a directory.
.SM
\%[ENOTDIR]
.IP
The named directory does not exist.
.SM
\%[ENOENT]
.IP
The effective user
.SM ID
is not super-user.
.SM
\%[EPERM]
.IP
.I Dirname
points outside the process's allocated address space.
.SM
\%[EFAULT]
.SH RETURN VALUE
Upon successful completion, a value of 0 is returned.
Otherwise, a value of \-1 is returned and
.B errno
is set to indicate the error.
.SH ASSEMBLER
.nf
.na

	CONSTANT CHROOT	:= 61
	...		!* dirname in r0 *!
			!* (if segmented: dirname in rr0) *!
	clr	r4
	sc	#CHROOT
	...		!* return value in r4 *!
	   		!* carry flag set if error *!
.fi
