.po 1i
.TH ADVENTURE 6 Zilog
.V 08/15/84 17:36:40
.\"@[$]adventure.6	1.5	08/15/84 17:36:40 - Zilog Inc.
.ad
.fi
.SH NAME
adventure
.SH SYNOPSIS
.B adventure
.SH DESCRIPTION
.B Adventure
is a treasure hunt game.
General directions are given at the beginning of the game.
The computer prompts for answers and directions in response
to the descriptions given regarding location.
Commands can be one or two words long, but only the first
five letters of each word are read.
Typing 
.B help
produces a list of general hints.
Creating a map while playing the game is very useful.
.SH LIMITATIONS
The list of commands is limited.
The list of hints is very limited and general.
One must be quite imaginative to succeed.
.SH FILES
/usr/games/adventure	the program

