.po 1i
.TH BACKGAMMON 6 Zilog
.V 08/15/84 17:36:42
.\"@[$]backgammon.6	1.3	08/15/84 17:36:42 - Zilog Inc.
.ad
.fi
.SH NAME
backgammon \- the game
.SH SYNOPSIS
.B backgammon
.SH DESCRIPTION
This program does what you expect.
It will ask whether you need instructions.
.SH FILES
/usr/games/backgammon	the program

