.po 1i
.TH FORTUNE 6 UCB
.V 08/15/84 17:36:48
.\"@[$]fortune.6	1.3	08/15/84 17:36:48 - Zilog Inc.
.ad
.fi
.SH NAME
fortune \- print fortune cookie
.SH SYNOPSIS
.B fortune
.SH DESCRIPTION
.B Fortune
emulates the well-known Chinese munchie-of-wisdom.
The program selects a line at random
from a text file.
Add or delete fortunes by adding or removing lines from this file.
.SH FILES
/usr/games/lib/fortunes \- wisdom file
.SH DIAGNOSTICS
The System 8000 does not trap memory errors.
.SH LIMITATIONS
Humor is subjective.
