.po 1i
.TH MV 7 Bell
.V 08/15/84 17:37:45
.\" @[$]mv.7	1.3	08/15/84 17:37:45 - Zilog Inc.
.ad
.fi
.SH NAME
mv \- a macro package for making view graphs
.SH SYNOPSIS
.B mvt
[\fIoptions\fR] [\fIfiles\fR]
.br
.B "troff \-mv"
[\fIoptions\fR] [\fIfiles\fR]
.SH DESCRIPTION
This package provides an easy-to-use facility for making view
graphs and projection slides in a variety of formats.
A dozen or so macros are provided that accomplish most of the
formatting tasks needed in making transparencies.
All of the facilities of
.BR troff (1),
.BR eqn (1),
and
.BR tbl (1)
are available for more difficult tasks.
The output can be previewed on most terminals, and,
in particular, on the Tektronix 4014
and on the Versatec printer.
See the reference below for further details.
.SH FILES
/usr/lib/tmac/tmac.v
.SH SEE ALSO
eqn(1),
mvt(1),
tbl(1),
troff(1).
