.po 1i
.TH CHGRP 1 Bell
.ad
.fi
.V 08/15/84 16:40:32
.\"@[$]chgrp.1	1.4	08/15/84 16:40:32 - Zilog Inc.
.SH NAME
chgrp \- change group
.SH SYNOPSIS
.B chgrp
\fIgroup file ...\fR
.SH DESCRIPTION
.B Chgrp
changes the group-ID of the
.I files
to
.IR group .
The group may be either a decimal group-ID number or
a group name found in the group-ID file.
.SH FILES
/etc/chgrp
.br
/etc/passwd
.br
/etc/group
.SH SEE ALSO
chown(1), chown(2),
passwd(5), group(5), chmog(M)
