.po 1i
.TH DAYTIME 1 UCB
.V 08/15/84 16:45:32
.\" @[$]daytime.1	1.6	08/15/84 16:45:32 - Zilog Inc.
.ad
.fi
.SH NAME
daytime \- give the time to human-reasonable accuracy
.SH SYNOPSIS
.B daytime
.SH DESCRIPTION
.B Daytime
prints out in English the current time of day,
accurate to the nearest five minutes.
.SH EXAMPLE
.RS
\fB % daytime\fR
.br
   Five after four
.RE
.SH LIMITATIONS
.B Daytime
depends on the user to determine whether it's currently night
or day.
