.po 1i
.TH DIRCMP 1 Zilog
.V 08/15/84 16:47:36
.\" @[$]dircmp.1	1.5	08/15/84 16:47:36 - Zilog Inc.
.ad
.af % 1
.fi
.SH NAME
dircmp \- directory comparison
.SH SYNOPSIS
.B dircmp
\fIdir1 dir2\fR
.SH DESCRIPTION
.B Dircmp\^
examines
.I dir1\^
and
.I dir2\^
and generates various tabulated information about 
the contents of the directories. 
Listings of files that are unique to each directory are 
generated in addition to a list that indicates whether the 
files common to both directories have the same contents.
.SH SEE ALSO
cmp(1), diff(1).
