.po 1i
.TH ECHO2 1 Zilog
.V 08/15/84 16:48:11
.\" @[$]echo2.1	1.9	08/15/84 16:48:11 - Zilog Inc.
.ad
.fi
.SH NAME
echo2 \- echo (print) arguments to standard error
.SH SYNOPSIS
.B echo2
[
.B -n
] [ 
.I arg
] \&...
.SH DESCRIPTION
.B Echo2
writes its arguments separated by blanks and terminated 
by a newline on the standard error. 
.SH OPTIONS
.TP
.B -n
No newline is added to the output.
.SH SEE ALSO
echo(1).
