.po 1i
.TH GETNAME 1 UCB
.V 08/15/84 16:53:01
.\" @[$]getNAME.1	1.6	08/15/84 16:53:01 - Zilog Inc.
.ad
.fi
.SH NAME
getNAME \- get NAME sections of manual for whatis/apropos data base
.SH SYNOPSIS
.B getNAME
\fIname ...
.SH DESCRIPTION
.B Getname
reads the first few lines of each of the argument manual section
sources, and finds the \&.TH entry and the .SH entry writing them
to the standard output in a form suitable for making into the
whatis/apropos data base.
.SH FILES
/usr/lib/whatis		Eventual data base
.SH SEE ALSO
apropos(1), makewhatis(1), whatis(1).
