.po 1i
.TH INTRO 1 Zilog
.V 08/15/84 16:35:35
.\" @[$]INTRO.1	1.7	08/15/84 16:35:35 - Zilog Inc.
.ad
.fi
.SH NAME
INTRO \- introduction to Section 1 commands
.SH SYNOPSIS
INTRO is not a command, it is a manual entry, therefore there
is no synopsis.
.SH DESCRIPTION
The commands described in Section 1 of the ZEUS Reference
Manual are available to all users and are typed into the
computer via the terminal keyboard.
The commands in each section of this manual are arranged
alphabetically.
Notations are made at the center of the foot of each command
page indicating the engineering source of the command.
These are:
.sp
.nf
     Notation:   Source:
.sp
     Bell        Bell Laboratories
     UCB         University of California, Berkeley
     Zilog       Zilog, Inc.
.fi
.sp
Reference to Section 1C as in the entry foreach(1C) refers
to commands that are internal to the C Shell.
.SH COMMAND SYNTAX
The description of each command (unless otherwise noted) uses
the following conventions:
.IP "\fBBoldface\fR" 15
Words in \fBbold\fR print are literals; they must be typed
into the terminal just as they appear on paper.
.IP \fIUnderlining\fR 15
Words that are \fIunderlined\fR can or must be replaced by words
of the user's choosing.
.IP "Brackets [ ]" 15
Words in brackets are options, they can appear in the command
line or can be omitted.
.IP "Ellipses ..." 15
Three dots in a row -- ("...") -- are used to note that the
preceding word can be repeated any number of times.
.IP "Quote Marks" 15
Double quotes are used to isolate special characters from
the body of the text.
.sp
Single front quotes are used to denote words with special
meaning, though they may not be actual commands.
.bp
Single back quotes are used by the computer to substitute
the output of a command for the command word itself.
.SH SEE ALSO
Section 0 -- Introduction to ZEUS Software Documentation
.br
ZEUS Reference Manual                          03-3255
.br
ZEUS Utilities Manual                          03-3250
.br
ZEUS Languages/Programming Tools Manual        03-3249
.br
ZEUS Administrator Manual                      03-3246
.br
PLZ/ASM Assembly Language Programming Manual   03-3055
.br
The C Programming Language                     03-3161
.sp
.SH LIMITATIONS
Regretfully, many command descriptions do not adhere to the
forementioned conventions.
