.po 1i
.TH LEX 1 Bell
.V 08/15/84 16:56:08
.\" @[$]lex.1	1.9	08/15/84 16:56:08 - Zilog Inc.
.ad
.fi
.SH NAME
lex \- generate programs for simple lexical tasks
.SH SYNOPSIS
.B lex
[
.B \-tvfn
] [ file ] ...
.SH DESCRIPTION
.B Lex\^
generates programs to be used in simple lexical analysis of text.
.PP
The input
.I files\^
(standard input default)
contain strings and expressions
to be searched for, and C text to be executed when
strings are found.
.PP
A C source program
.I lex.yy.c
is generated, to be compiled thus:
.IP
cc \-u \_main lex.yy.c \-ll
.LP
This program copies the input to the output
except when a string specified in the file is found; then
the corresponding program text is executed.
The actual string matched is left in
.IR yytext ,
an external character array.
.LP
Matching is done in order of the strings in the file.
The strings
may contain square brackets to indicate character classes,
as in
.I [abx\-z]
to indicate a
.I "a, b, x, y" 
and
.I "z"
and the operators
.BR \(** ", " + ", and " ?
mean respectively
any non-negative number of, any positive number of, and either
zero or one occurrences of, the previous character or character class.
The character
.B .
is the class of all
.SM ASCII
characters except new-line.
Parentheses for grouping and vertical bar for alternation are
also supported.
.LP
The notation
.I "r { d , e }"
in a rule indicates between
.I d\^
and
.I e\^
instances of regular expression
.IR r .
It has higher precedence than
.IR | ,
but lower than
.IR \(** ,
.IR ? ,
.IR + ,
and concatenation.
The character
.B ^
at the beginning of an expression
permits a
successful match only immediately after a new-line, and the character
.B $
at the end of an expression requires a trailing new-line.
The character
.B /
in an expression indicates trailing context;
only the part of the expression up to the slash
is returned in
.IR yytext ,
but the remainder of the expression must follow in the input stream.
An operator character may be used as an ordinary symbol
if it is within \fB"\fR
symbols or preceded by
.BR \e .
Thus
.I [a\-zA\-Z]+
matches a string of letters.
.PP
Three subroutines defined as macros are expected:
.B input()
to read a character;
.BI unput( c )
to replace a character read; and
.BI output( c )
to place
an output character.  They are defined in terms
of the standard streams,
but you can override them.
.LP
The program generated is named
.BR yylex() ,
and the library contains a
.B main()
which calls it.
The action
.SM REJECT
on the right side of the rule causes this
match to be rejected and the next suitable match executed;
the function
.B yymore()
accumulates additional characters
into the same
.IR yytext ;
and the function
.BI yyless( p )
pushes
back the portion of the string matched beginning at
.IR p ,
which
should be between
.I yytext\^
and
.IR yytext + yyleng .
The macros
.I input\^
and
.I output\^
use files
.B yyin
and
.B yyout
to read from and write to,
defaulted to
.B stdin
and
.BR stdout ,
respectively.
.PP
Any line beginning with a blank is assumed
to contain only C text and is copied; if it precedes
.B %%
it is copied into the external definition area of the
.I lex.yy.c
file.
All rules should follow a
.BR %% ,
as in
.SM YACC.
Lines preceding
.B %%
which begin with a non-blank character define
the string on the left to be the remainder of
the line; it can be called out later by surrounding it with
.BR {} .
.LP
\fBNote\fR that curly brackets do not imply parentheses;
only string substitution is done.
.SH EXAMPLES
.ta +8n +8n +8n +8n
.nf
	D	[0\-9]
	%%
	if	printf("\s-1IF\s+1 statement\\n");
	[a\-z]+	printf("tag, value %s\\n",yytext);
	0{D}+	printf("octal number %s\\n",yytext);
	{D}+	printf("decimal number %s\\n",yytext);
	"++"	printf("unary op\\n");
	"+"	printf("binary op\\n");
	"/\(**"	{	loop:
			while (input() != \(fm\(**\(fm);
			switch (input())
				{
				case \(fm/\(fm: break;
				case \(fm\(**\(fm: unput(\(fm\(**\(fm);
				default: go to loop;
				}
			}
.fi
.PP
The following
.B lex
program converts upper case to lower,
removes blanks at the end of lines,
and replaces multiple blanks by single blanks.
.IP ""
.nf
.ta \w'[A\-Z] 'u
%%
[A\-Z]	putchar(yytext[0]+\'a\'\-\'A\');
[ ]+$	;
[ ]+	putchar(\' \');
.fi
.PP
The external names generated by
.B lex\^
all begin with the prefix
.BR yy " or " YY .
.PP
The options have the following meanings.
.TP
.B \-t
Place the result on the standard output instead of in file
.I lex.yy.c .
.TP
.B \-v
Print a one-line summary of statistics of the generated analyzer.
.TP
.B \-n
Opposite of
.BR \-v ;
.B  \-n
is default;
.TP
.B \-f
`Faster' compilation: don't bother to pack
the resulting tables; limited to small programs.
.PP
Multiple files are treated as a single file.
If no files are specified,
standard input is used.
.PP
Certain table sizes for the resulting finite state machine
can be set in the definitions section:
.RS
.TP "@.TP
.BI %p " n\^"
number of positions is
.I n\^
(default 2000)
.ns
.TP
.BI %n " n\^"
number of states is
.I n\^
(500)
.ns
.TP
.BI %t " n\^"
number of parse tree nodes is
.I n\^
(1000)
.ns
.TP
.BI %a " n\^"
number of transitions is
.I n\^
(3000)
.RE
.PP
The use of one or more of the above automatically implies the
.B \-v
option,
unless the
.B \-n
option is used.
.SH SEE ALSO
yacc(1).
.br
.I "\s-1LEX\s+1 \- Lexical Analyzer Generator\^"
in the ZEUS Languages / Programming Tools Manual
