.po 1i
.TH LOGNAME 1 Bell
.V 08/15/84 16:57:00
.\" @[$]logname.1	1.8 08/15/84 16:57:00 - Zilog Inc.
.ad
.fi
.SH NAME
logname \- get login name
.SH SYNOPSIS
.B logname
.SH DESCRIPTION
.B Logname\^
returns the contents of the environment variable \fB$LOGNAME\fR,
which is set when a user logs into the system.
.SH SEE ALSO
env(1),
login(1),
logname(3),
environ(5).
