.po 1i
.TH LPR 1 Bell
.V 08/15/84 16:57:14
.\" @[$]lpr.1	1.7	08/15/84 16:57:14 - Zilog Inc.
.ad
.fi
.SH NAME
lpr  \- line printer spooler
.SH SYNOPSIS
.B lpr
[ \fIoption\fR ] ... [ \fIfile\fR ] ...
.SH DESCRIPTION
.B Lpr
is now linked to 
.B nq(1).
Please refer to this page in the manual
for more information.
