.po 1i
.TH OBJHDR 1 Zilog
.V 08/15/84 17:00:23
.\" @[$]objhdr.1	1.6	08/15/84 17:00:23 - Zilog Inc.
.ad
.fi
.SH NAME
objhdr \- object module header dump
.SH SYNOPSIS
.B objhdr
\fIfile\fR
.SH DESCRIPTION
.B Objhdr
is specifically designed for dumping S8000 load module
header information in hex format.
.SH SEE ALSO
nm(1), a.out(5), od(1), objdu(1).
