.po 1i
.TH PWD 1 Bell

.V 08/15/84 17:01:52
.\" @[$]pwd.1	1.6 08/15/84 17:01:52 - Zilog Inc.
.ad
.fi
.SH NAME
pwd \- print present working directory name
.SH SYNOPSIS
.B pwd
.SH DESCRIPTION
.B Pwd\^
prints the path name of the working (current) directory.
.SH SEE ALSO
cd(1).
.SH DIAGNOSTICS
\&"cannot open .." and "read error in .." indicate
possible file system trouble or no permission for directory access.
