.po 1i
.TH SCC 1 Zilog
.V 08/15/84 17:03:09 
.\" @[$]scc.1	1.29 08/15/84 17:03:09 - Zilog Inc. 
.ad
.fi
.SH NAME
scc \- System 8000 segmented C compiler
.SH SYNOPSIS
.B scc
[ \fIoptions\fR ]  \fIfile\fR ...
.SH DESCRIPTION
.B Scc
is a segmented C "stage" compiler that produces Z8001 code.
A "stage" compiler produces
object code from source code in stages. These
can be strung together without interruption, providing a virtual continuity to
the compilation, 
or the compilation can be halted at the termination of any of the stages.
In the latter case,
the uninitiated stages can be executed later as stand-alone tasks
resulting in modules for input to the next stage 
(or resulting in the executable load module, if the last stage). 
.sp
The stages are the compilation, the assembly, and the linkage.
Consequently, 
depending on the options, a single 
.B scc
call can compile; compile and assemble; or compile, assemble, and link.
.PP
The
.B scc
compiler provides an unsigned char data type,
initialized bit fields, the ZEUS Version 7 features of C (structure 
assignments and enumeration types), and the new ZEUS System III additions
to the C language: 1) the "void" data type; 2) the unique identification of
names of structure and union members.
.SH COMPILE/ASSEMBLE/LINK
Each C source file ending in \&.c is compiled by \fBscc\fR, producing a 
corresponding Z8000 
assembly-language
source file ending in \&.s. The
\&.s files are assembled by the Z8000 assembler \fBcas\fR(1),
producing un-linked object modules
ending in \&.o. The \&.o files, along with any other C-compatible object
modules or libraries specified, are passed to the segmented linking-loader
\fBsld\fR(1), which links them in the order given, producing a load module whose 
default name is a.out. 
.SH COMPILE/ASSEMBLE
With a \fB-c\fR option, the stage transaction halts after the
\&.s Z8000 assembly-language source files produced by \fBscc\fR are assembled 
by \fBcas\fR, producing corresponding unlinked object modules whose  
names end in \&.o.
.SH COMPILE
With an \fB-S\fR option, the stage transaction halts after \fBscc\fR
produces a Z8000 assembly-language source file ending in \&.s for each C
source file ending in \&.c.
.bp
.SH OPTIONS
Specified options may be directed at the compiler or the
linking-loader (\fBscc\fR and \fBsld\fR, respectively). 
\fBScc\fR passes \fBcas\fR the \fB-o\fR option and its argument, if specified.
.SH Compiler-Directed Options
.TP
.B \-c
Compile and assemble the named C source files but suppress
the linking step.
A \&.o object module is produced for each \&.c source file.
.TP
.BI \-D name
.ti -5
.BI \-D name=def
.br
Define
.I name
to the preprocessor, as if by #define.
If no definition is given,
.I name
is defined as 1.
.TP
.B \-E
Run only the macro preprocessor
and send the result to the standard output.
.TP
.B \-F
Invoke the Faster Floating Point (FFP) Library Package, which is available
as an option.
.TP
.BI \-I dir
Bring in a directory of #include files.
Names that do not begin with / are always
sought first in the same directory as the source file,
then in directories named in 
.B -I
options, then in directories belonging to a standard list.
.TP 
.B \-O
Invoke the System 8000 C optimizer. 
.TP
.B \-p
The compiler will produce code that counts
the number of times each routine is called.  
If loading takes place, the standard
startup routine will be replaced  by one which automatically calls
\fBsegmon\fR(3) at the start. 
A \fBmon.out\fR(5) file will be written out at normal termination of
execution of the object program.
An execution profile can then be generated by use
of \fBsprof\fR(1).
(Note: The \fB\-p\fR option produces an execution profile itself;  
but that profile should not be used because necessary, related programs 
are not supplied for the System 8000.)
.TP
.B \-P
Run only the macro preprocessor and place the result for
each \&.c file in a corresponding \&.i file with no # lines in it.
.TP
\fB \-S\fR [\fBl\fR]
Compile the named C source files but suppress the 
assembly and link step.
Leave the assembly language code in corresponding files ending in \&.s.
If 
.B l 
(el) is specified, make the original C source lines appear as assembly
language comments preceding the assembly code produced for them.
.TP
.BI \-U name
Remove any initial definition of 
.IR name .
.PP
.SH Loader-Directed Options
.TP 
.BI \-l libname 
Search the library archive directory /lib for the library whose name
is \fBslib\fIlibname\fB.a\fR. For example, to search the math library
slibm.a, the specification is \fB-lm\fR;
to search libld.a, use
.BR \-lld .
This option is specified
during compilation (the last argument on the line) when the compilation,
assembly, and linkage is performed in a stream.
If linkage is performed
separately from compilation, the \fB-l\fR option is specified at link-time
(see \fBsld\fR(1)).  
.sp
Other options can be specified on the 
.B scc 
call and are passed to the linker
.BR sld .
See the description of 
.BR ld (1)
for a description of these options. (Note: not \fBsld\fR because the
segment-mapping options cannot be specified at compile-time).
.sp
Note also that an internal call to the linker
provides the options
.BR \-z ,
.BR \-X ,
and
.B \-e
with entry name \fBstart\fR, and adds the library name /lib/slibc.a
to the end of the list of object module names. Consequently, these mandatory 
options are not specified at the command level.
.sp
.B Sld
and
.B ld
recognize the same set of options passed to them by the C compiler.
.SH EXAMPLES
.nf
             \fBscc fourier.c -lm\fR
.sp
.fi
The above example compiles fourier.c, including the math library /lib/slibm.a
during compilation. 
.nf
.sp 
             \fBscc -Sl prog1.c prog2.c prog3.c\fR
.sp
.fi
The above example compiles prog1.c, prog2.c, and prog3.c, producing,
respectively, assembly-language source files prog1.s, prog2.s, and prog3.s. 
The C source lines appear
as comments above the assembly-language blocks produced for them.
.nf
.sp
             \fBscc -O -I/path/path/mylibs -o OUTPUT  \ 
             src1.c src2.c src3.c -lm\fR
.sp
.fi
The above example (which must be typed as a single command line) compiles,
assembles, and links src1.c, src2.c, and src3.c. 
One or more of
these source files define "include" statements referencing a library
located in the /path/path/mylibs directory. Consequently, the path to
the sought directory must be established for the compiler with a
\fB-I\fR specification. The \fB-O\fR option causes the global optimizer to be
executed against each source module. The standard library slibm.a is
specified for searching during linkage (Note: the trailing position of the
\fB-l\fR specification is critical). The load module created
by the linking-loader is named OUTPUT.
.SH FILES
file.c		source file
.br
file.o		object file
.br
a.out		load module
.br
/tmp/cc.? 	temporaries
.br
/lib/cpp  	preprocessor
.br
/lib/scparse   compiler pass1
.br
/lib/scodgen   compiler pass2
.br
/lib/spopt     optional optimizer
.br
/lib/clist     optional listing pass
.br
/lib/slibc.a	standard library
.br
/lib/smcrt0.o	optional startup routine for profiling
.br
/lib/scrt0.o   segmented C runtime startup routine
.SH SEE ALSO
.nf
cas(1), ld(1).
.sp
\fIThe C Programming Language\fR - B. W. Kernighan and D. M. Ritchie,
Prentice-Hall, 1978,
\fIThe System 8000 Calling Conventions\fR, and
\fIThe C Programming Language\fR, in the ZEUS Languages/Programming
Tools Manual.
.SH COMPARE
cc(1)
.SH DIAGNOSTICS
The diagnostics produced by the compiler, 
assembler, or linker 
are self-explanatory.
.SH IMPLEMENTATION
.PP
The
.B scc
compiler has the following characteristics:
.RS
.IP "\ \(bu"
As many as six register declarations can be honored, rather
than three, as on the PDP-11.
The Z8001 registers r8 through r13 can be used for register variables.
.IP "\ \(bu"
The \fBscc\fR compiler produces object code which conforms to the System
8000 calling conventions.
.IP "\ \(bu"
The name 'z8000' is predefined in the 
C preprocessor to be the constant 1.
.RE
.DT
