.po 1i
.TH TROFF 1 Bell 
.V 08/15/84 17:08:02
.\"   @[$]troff.1	1.15  08/15/84 17:08:02 - Zilog Inc. 
.ad
.fi
.SH NAME
troff, nroff \- typeset or format text
.SH SYNOPSIS
.B nroff
[ 
.I options\^ 
] 
[ 
.I files\^ 
]
.PP
.B troff
[ 
.I options\^  
] 
[ 
.I files\^  
]
.SH DESCRIPTION
.B Nroff
formats text contained in the specified argument 
.I files\^. 
If no filenames are given, the default argument is standard input.
Data from standard input can be interspersed with data from argument
files by specifying a 
.RB ( \- ) 
on the commandline where data should be expected from standard input.
A ctrl-d entered to terminate the passing of data from standard input
results in data being accepted from the next commandline argument,
if one is specified.  
.sp
\fBNroff\fR prints its input on 
typewriter-like devices
and line printers;
the device-dependent \fBtroff\fR 
formats text
for a Wang Laboratories, Inc., C/A/T phototypesetter. However, a 
device-independent
version of \fBtroff\fR now enables the creation of device drivers 
for many other
typesetters.
\fBnroff\fR's and \fBtroff\fR's capabilities are described in 
\fIA Troff Tutorial\fR and
the \fINroff User's Manual\fR.
.SH OPTIONS
The
.IR options 
may appear in any order, but must appear
before the
.IR files . 
.PP
.PD 0
.sp
.TP
.BI \-c name\^
Prepend to the input
.na
.I files\^
the compacted macro files
.BR /usr/lib/macros/cmp. [ nt ] .\c
.RB [ dt ] .\f2name\fP\^
and
.BR /usr/lib/macros/ucmp. [ nt ] .\f2name\fP\^ .
.ad
.sp
.TP
.B \-i
Read standard input after
.I files\^
are exhausted.
.sp
.TP
.BI \-k name\^
Compact the macros used in this
invocation of
.B nroff\^/\^troff,
placing the output in files
.RB [ dt ] .\f2name\fP\^
in the current directory.
.sp
.TP
.BI \-m name\^
Prepend to the input
.I files\^
the non-compacted (\s-1ASCII\s+1 text) macro file
.BI /usr/lib/tmac/tmac. name\^\f1.\fP
.sp
.TP
.BI \-n N
Number first generated page
.IR N .
.sp
.TP
.BI \-o list
Print only pages whose page numbers appear in
the
.I list\^
of numbers and ranges, separated by commas.
A range
.IB N \- M\^
means pages
.I N\^
through
.IR M ;
an initial
.BI \- N\^
means
from the beginning to page
.IR N ;
and a final
.IB N \-
means
from
.I N\^
to the end.
(See \fBLIMITATIONS\fR).
.sp 
.TP
.B \-q
Invoke the simultaneous input-output mode of the
.B \&.rd
request.
.sp
.TP
.BI \-r aN\^
Set register
.I a\^
(which must have a one-character name) to
.IR N .
.sp	
.TP
.BI \-s N\^
Stop every
.B N
pages.
.B Nroff
will halt after every
.I N\^
pages (default
.IR N =1)
to allow paper loading or
changing, and will resume upon receipt of a line-feed or new-line
(new-lines do not work in pipelines, e.g., with \fBmm\fR(1)).
This option does not work if the output of
.B nroff
is piped through \fBcol\fR(1).
.B Troff
will stop the phototypesetter every
.I N\^
pages,
produce a trailer to allow changing cassettes,
and resume when the typesetter's start button is pressed.
When \fBnroff (troff)\fR halts between pages, an ASCII BEL
(in \fBtroff\fR, the message "page stop") is sent to the terminal.
.sp 
.TP
.B \-z
Print only messages generated by
.B \&.tm
(terminal message)
requests.
.PD
.SS Nroff only:
.PP
.PD 0
.sp
.TP
.B \-e
Produce equally-spaced words in adjusted
lines, using the full resolution of the particular terminal.
.sp
.TP
.B \-h
Use output tabs during horizontal spacing
to speed output and reduce output character count.
Tab settings are assumed to be every
8 nominal character widths.
.sp
.TP
.BI \-T name\^
Prepare output for specified terminal.
Known
.IR name s
are
.B 37
for the (default)
.SM TELETYPE\*S\*R
Model 37 terminal,
.B tn300
for the
.SM GE
TermiNet\ 300 (or any terminal without half-line
capability),
.B 300s
for the
.SM DASI
300s,
.B 300
for the
.SM DASI
300,
.B 450
for the
.SM DASI
450,
.B lp
for a (generic)
.SM ASCII
line printer,
.B 382
for the
.SM DTC\*S-382,
.B 4000A
for the Trendata 4000A,
.B 832
for the Anderson Jacobson 832,
.B X
for a (generic)
.SM EBCDIC
printer, and
.B 2631
for the Hewlett Packard 2631 line printer.
.sp
.TP
.BI \-u n\^
Set the emboldening factor (number of character overstrikes) for the
third font position (bold) to
.IR n ,
or to zero if
.I n\^
is missing.
.PD
.SS Troff only:
.PP
.PD 0
.sp
.TP   
.B \-a
Send a printable
.SM ASCII
approximation
of the results to the standard output.
.sp
.TP
.B \-b
Report whether the phototypesetter
is busy or available.
No text processing is done.
.sp
.TP
.B \-f
Refrain from feeding out paper and stopping
phototypesetter at the end of the run.
.sp
.TP
.B \-g
Prepare output for the Murray Hill
Computation Center phototypesetter and direct it to the standard output
This option is not compatible with the
.B \-s
option;
furthermore, when this option is invoked, all
.B \&.fp
(font position)
requests (if any) in the
.B troff
input
must come before the first break, and no
.B \&.tl
requests may come before the first break.
.sp
.TP
.BI \-p N\^
Print all characters in point size
.I N\^
while retaining all prescribed spacings and motions,
to reduce phototypesetter elapsed time.
.br
.ne 2
.sp
.TP
.B \-t
Direct output to the standard output instead
of to the phototypesetter.
.sp
.TP
.BI \-T name\^
Use font-width tables for device
.I name\^
(the font tables are found in
.BI /usr/lib/font/ name /\(**\f1).
Currently, no
.IR name s
are supported.
.sp
.TP
.B \-w
Wait until phototypesetter is available, if
it is
currently busy.
.PD
.SH FILES
.ta \w'/usr/lib/tmac/tmac\f3.\fP\(**\ \ 'u
.PD 0
/usr/lib/suftab        suffix hyphenation tables 
.PP
/tmp/ta$#              temporary file 
.PP
/usr/lib/tmac/tmac\f3.\fP\(**   standard macro files and pointers 
.PP
/usr/lib/macros/\(**      standard macro files 
.PP
/usr/lib/term/\(**        terminal driving tables for 
.I nroff\^
.PP
/usr/lib/font/\(**        font width tables for
.I troff\^
.PD
.DT
.SH SEE ALSO
.PD 0
\fIN\s-1ROFF\s+1 User's Manual\^\fR and \fIA T\s-1ROFF\s+1 Tutorial\^\fR
in the ZEUS Utilities Manual.
.PP
eqn(1), tbl(1), mm(7).
.PP
col(1), greek(1), mm(1)
( \fBnroff\fR only).
.PP
mmt(1), tc(1), mv(7)
( \fBtroff\fR only).
.PD
.SH LIMITATIONS  
.B Nroff\^/\^troff\^
believes in Eastern Standard Time; as a result, depending on the
time of the year and on your local time zone, the date that
.B nroff\^/\^troff\^
generates may be off by one day.
.br
.sp
When
.B nroff\^/\^troff\^
is used with the
.BI \-o list\^
option inside a pipeline
(e.g., with one or more of \fBcw\fR(1), \fBeqn\fR(1),
and \fBtbl\fR(1)), it may cause a harmless "broken pipe" diagnostic
if the last page of the document is not specified in \fIlist\fR.
