.po 1i
.TH USERS 1 Zilog
.V 08/15/84 17:08:54
.\" @[$]users.1	1.5	08/15/84 17:08:54 - Zilog Inc.
.ad
.fi
.SH NAME
users \- compact list of users who are on the system
.SH SYNOPSIS
.B users
.SH DESCRIPTION
.B Users
lists the login names of the users currently on the system in a compact,
one-line format.
.SH FILES
/etc/utmp
.SH SEE ALSO
who(1), whodo(1), whois(1), whoami(1).
